name: Setup
description: Set up the environment for the project

inputs:
  restore-turbo-cache-key:
    description: 'Additional cache key part to find the turbo cache from an earlier job'
    default: 'default'
  turbo-cache-key:
    description: 'Additional cache key part to use for sharing the updated turbo cache with subsequent jobs'
    default: 'default'

runs:
  using: 'composite'
  steps:
    - name: Cache bun
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: |
          ~/.bun
        key: ${{ runner.os }}-${{ runner.arch }}-bun-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-bun-

    - name: Install tools
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3

    - name: Cache node modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      id: node-cache
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ hashFiles('**/package.json', 'bun.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-node-

    - name: Cache turbo
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: |
          .turbo/cache
        key: ${{ runner.os }}-${{ runner.arch }}-turbo-${{ inputs.turbo-cache-key }}-${{ github.event.pull_request.head.sha || github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-turbo-${{ inputs.restore-turbo-cache-key }}-${{ github.event.pull_request.head.sha || github.sha }}
          ${{ runner.os }}-${{ runner.arch }}-turbo-${{ inputs.turbo-cache-key }}-
          ${{ runner.os }}-${{ runner.arch }}-turbo-${{ inputs.restore-turbo-cache-key }}-
          ${{ runner.os }}-${{ runner.arch }}-turbo-

    - run: bun install
      shell: bash
